
package com.quickstart.test.webservice.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceHello", targetNamespace = "http://service.example.webservice.test.yang.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceHello {

    /**
     * 
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://service.example.webservice.test.yang.com/", className = "com.yang.test.webservice.example.client.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://service.example.webservice.test.yang.com/", className = "com.yang.test.webservice.example.client.GetValueResponse")
    public String getValue(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
