
package org.quickstart.webservice.jws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://server.jws.webservice.quickstart.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://server.jws.webservice.quickstart.org/", className = "org.quickstart.webservice.jws.server.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.jws.webservice.quickstart.org/", className = "org.quickstart.webservice.jws.server.AddResponse")
    @Action(input = "http://server.jws.webservice.quickstart.org/IMyService/addRequest", output = "http://server.jws.webservice.quickstart.org/IMyService/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.quickstart.webservice.jws.server.User
     */
    @WebMethod
    @WebResult(name = "loginUser", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://server.jws.webservice.quickstart.org/", className = "org.quickstart.webservice.jws.server.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://server.jws.webservice.quickstart.org/", className = "org.quickstart.webservice.jws.server.LoginResponse")
    @Action(input = "http://server.jws.webservice.quickstart.org/IMyService/loginRequest", output = "http://server.jws.webservice.quickstart.org/IMyService/loginResponse")
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minusResult", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://server.jws.webservice.quickstart.org/", className = "org.quickstart.webservice.jws.server.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://server.jws.webservice.quickstart.org/", className = "org.quickstart.webservice.jws.server.MinusResponse")
    @Action(input = "http://server.jws.webservice.quickstart.org/IMyService/minusRequest", output = "http://server.jws.webservice.quickstart.org/IMyService/minusResponse")
    public int minus(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
